# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Union
from . import utilities, tables

class GetLbIPBetaResult:
    """
    A collection of values returned by getLbIPBeta.
    """
    def __init__(__self__, id=None, ip_address=None, ip_id=None, lb_id=None, organization_id=None, region=None, reverse=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        __self__.id = id
        """
        The provider-assigned unique ID for this managed resource.
        """
        if ip_address and not isinstance(ip_address, str):
            raise TypeError("Expected argument 'ip_address' to be a str")
        __self__.ip_address = ip_address
        if ip_id and not isinstance(ip_id, str):
            raise TypeError("Expected argument 'ip_id' to be a str")
        __self__.ip_id = ip_id
        if lb_id and not isinstance(lb_id, str):
            raise TypeError("Expected argument 'lb_id' to be a str")
        __self__.lb_id = lb_id
        if organization_id and not isinstance(organization_id, str):
            raise TypeError("Expected argument 'organization_id' to be a str")
        __self__.organization_id = organization_id
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        __self__.region = region
        if reverse and not isinstance(reverse, str):
            raise TypeError("Expected argument 'reverse' to be a str")
        __self__.reverse = reverse
class AwaitableGetLbIPBetaResult(GetLbIPBetaResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetLbIPBetaResult(
            id=self.id,
            ip_address=self.ip_address,
            ip_id=self.ip_id,
            lb_id=self.lb_id,
            organization_id=self.organization_id,
            region=self.region,
            reverse=self.reverse)

def get_lb_ip_beta(ip_address=None,ip_id=None,opts=None):
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()


    __args__['ipAddress'] = ip_address
    __args__['ipId'] = ip_id
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = utilities.get_version()
    __ret__ = pulumi.runtime.invoke('scaleway:index/getLbIPBeta:getLbIPBeta', __args__, opts=opts).value

    return AwaitableGetLbIPBetaResult(
        id=__ret__.get('id'),
        ip_address=__ret__.get('ipAddress'),
        ip_id=__ret__.get('ipId'),
        lb_id=__ret__.get('lbId'),
        organization_id=__ret__.get('organizationId'),
        region=__ret__.get('region'),
        reverse=__ret__.get('reverse'))
