// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type AccountSSHKey struct {
	pulumi.CustomResourceState

	// The name of the SSH key
	Name pulumi.StringOutput `pulumi:"name"`
	// The organization_id you want to attach the resource to
	OrganizationId pulumi.StringOutput `pulumi:"organizationId"`
	// The public SSH key
	PublicKey pulumi.StringOutput `pulumi:"publicKey"`
}

// NewAccountSSHKey registers a new resource with the given unique name, arguments, and options.
func NewAccountSSHKey(ctx *pulumi.Context,
	name string, args *AccountSSHKeyArgs, opts ...pulumi.ResourceOption) (*AccountSSHKey, error) {
	if args == nil || args.PublicKey == nil {
		return nil, errors.New("missing required argument 'PublicKey'")
	}
	if args == nil {
		args = &AccountSSHKeyArgs{}
	}
	var resource AccountSSHKey
	err := ctx.RegisterResource("scaleway:index/accountSSHKey:AccountSSHKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAccountSSHKey gets an existing AccountSSHKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAccountSSHKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AccountSSHKeyState, opts ...pulumi.ResourceOption) (*AccountSSHKey, error) {
	var resource AccountSSHKey
	err := ctx.ReadResource("scaleway:index/accountSSHKey:AccountSSHKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AccountSSHKey resources.
type accountSSHKeyState struct {
	// The name of the SSH key
	Name *string `pulumi:"name"`
	// The organization_id you want to attach the resource to
	OrganizationId *string `pulumi:"organizationId"`
	// The public SSH key
	PublicKey *string `pulumi:"publicKey"`
}

type AccountSSHKeyState struct {
	// The name of the SSH key
	Name pulumi.StringPtrInput
	// The organization_id you want to attach the resource to
	OrganizationId pulumi.StringPtrInput
	// The public SSH key
	PublicKey pulumi.StringPtrInput
}

func (AccountSSHKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*accountSSHKeyState)(nil)).Elem()
}

type accountSSHKeyArgs struct {
	// The name of the SSH key
	Name *string `pulumi:"name"`
	// The organization_id you want to attach the resource to
	OrganizationId *string `pulumi:"organizationId"`
	// The public SSH key
	PublicKey string `pulumi:"publicKey"`
}

// The set of arguments for constructing a AccountSSHKey resource.
type AccountSSHKeyArgs struct {
	// The name of the SSH key
	Name pulumi.StringPtrInput
	// The organization_id you want to attach the resource to
	OrganizationId pulumi.StringPtrInput
	// The public SSH key
	PublicKey pulumi.StringInput
}

func (AccountSSHKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*accountSSHKeyArgs)(nil)).Elem()
}
