// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type BaremetalServer struct {
	pulumi.CustomResourceState

	// Some description to associate to the server, max 255 characters
	Description pulumi.StringPtrOutput `pulumi:"description"`
	Domain      pulumi.StringOutput    `pulumi:"domain"`
	// Hostname of the server
	Hostname pulumi.StringPtrOutput       `pulumi:"hostname"`
	Ips      BaremetalServerIpArrayOutput `pulumi:"ips"`
	// Name of the server
	Name pulumi.StringOutput `pulumi:"name"`
	// ID of the server offer
	Offer pulumi.StringOutput `pulumi:"offer"`
	// ID of the server offer
	OfferId pulumi.StringOutput `pulumi:"offerId"`
	// The organization_id you want to attach the resource to
	OrganizationId pulumi.StringOutput `pulumi:"organizationId"`
	// The base image of the server
	Os pulumi.StringOutput `pulumi:"os"`
	// The base image id of the server
	OsId pulumi.StringOutput `pulumi:"osId"`
	// Array of SSH key IDs allowed to SSH to the server
	SshKeyIds pulumi.StringArrayOutput `pulumi:"sshKeyIds"`
	// Array of tags to associate with the server
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
	// The zone you want to attach the resource to
	Zone pulumi.StringOutput `pulumi:"zone"`
}

// NewBaremetalServer registers a new resource with the given unique name, arguments, and options.
func NewBaremetalServer(ctx *pulumi.Context,
	name string, args *BaremetalServerArgs, opts ...pulumi.ResourceOption) (*BaremetalServer, error) {
	if args == nil || args.Offer == nil {
		return nil, errors.New("missing required argument 'Offer'")
	}
	if args == nil || args.Os == nil {
		return nil, errors.New("missing required argument 'Os'")
	}
	if args == nil || args.SshKeyIds == nil {
		return nil, errors.New("missing required argument 'SshKeyIds'")
	}
	if args == nil {
		args = &BaremetalServerArgs{}
	}
	var resource BaremetalServer
	err := ctx.RegisterResource("scaleway:index/baremetalServer:BaremetalServer", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBaremetalServer gets an existing BaremetalServer resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBaremetalServer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BaremetalServerState, opts ...pulumi.ResourceOption) (*BaremetalServer, error) {
	var resource BaremetalServer
	err := ctx.ReadResource("scaleway:index/baremetalServer:BaremetalServer", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BaremetalServer resources.
type baremetalServerState struct {
	// Some description to associate to the server, max 255 characters
	Description *string `pulumi:"description"`
	Domain      *string `pulumi:"domain"`
	// Hostname of the server
	Hostname *string             `pulumi:"hostname"`
	Ips      []BaremetalServerIp `pulumi:"ips"`
	// Name of the server
	Name *string `pulumi:"name"`
	// ID of the server offer
	Offer *string `pulumi:"offer"`
	// ID of the server offer
	OfferId *string `pulumi:"offerId"`
	// The organization_id you want to attach the resource to
	OrganizationId *string `pulumi:"organizationId"`
	// The base image of the server
	Os *string `pulumi:"os"`
	// The base image id of the server
	OsId *string `pulumi:"osId"`
	// Array of SSH key IDs allowed to SSH to the server
	SshKeyIds []string `pulumi:"sshKeyIds"`
	// Array of tags to associate with the server
	Tags []string `pulumi:"tags"`
	// The zone you want to attach the resource to
	Zone *string `pulumi:"zone"`
}

type BaremetalServerState struct {
	// Some description to associate to the server, max 255 characters
	Description pulumi.StringPtrInput
	Domain      pulumi.StringPtrInput
	// Hostname of the server
	Hostname pulumi.StringPtrInput
	Ips      BaremetalServerIpArrayInput
	// Name of the server
	Name pulumi.StringPtrInput
	// ID of the server offer
	Offer pulumi.StringPtrInput
	// ID of the server offer
	OfferId pulumi.StringPtrInput
	// The organization_id you want to attach the resource to
	OrganizationId pulumi.StringPtrInput
	// The base image of the server
	Os pulumi.StringPtrInput
	// The base image id of the server
	OsId pulumi.StringPtrInput
	// Array of SSH key IDs allowed to SSH to the server
	SshKeyIds pulumi.StringArrayInput
	// Array of tags to associate with the server
	Tags pulumi.StringArrayInput
	// The zone you want to attach the resource to
	Zone pulumi.StringPtrInput
}

func (BaremetalServerState) ElementType() reflect.Type {
	return reflect.TypeOf((*baremetalServerState)(nil)).Elem()
}

type baremetalServerArgs struct {
	// Some description to associate to the server, max 255 characters
	Description *string `pulumi:"description"`
	// Hostname of the server
	Hostname *string `pulumi:"hostname"`
	// Name of the server
	Name *string `pulumi:"name"`
	// ID of the server offer
	Offer string `pulumi:"offer"`
	// The organization_id you want to attach the resource to
	OrganizationId *string `pulumi:"organizationId"`
	// The base image of the server
	Os string `pulumi:"os"`
	// Array of SSH key IDs allowed to SSH to the server
	SshKeyIds []string `pulumi:"sshKeyIds"`
	// Array of tags to associate with the server
	Tags []string `pulumi:"tags"`
	// The zone you want to attach the resource to
	Zone *string `pulumi:"zone"`
}

// The set of arguments for constructing a BaremetalServer resource.
type BaremetalServerArgs struct {
	// Some description to associate to the server, max 255 characters
	Description pulumi.StringPtrInput
	// Hostname of the server
	Hostname pulumi.StringPtrInput
	// Name of the server
	Name pulumi.StringPtrInput
	// ID of the server offer
	Offer pulumi.StringInput
	// The organization_id you want to attach the resource to
	OrganizationId pulumi.StringPtrInput
	// The base image of the server
	Os pulumi.StringInput
	// Array of SSH key IDs allowed to SSH to the server
	SshKeyIds pulumi.StringArrayInput
	// Array of tags to associate with the server
	Tags pulumi.StringArrayInput
	// The zone you want to attach the resource to
	Zone pulumi.StringPtrInput
}

func (BaremetalServerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*baremetalServerArgs)(nil)).Elem()
}
