// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetBaremetalOffer(ctx *pulumi.Context, args *GetBaremetalOfferArgs, opts ...pulumi.InvokeOption) (*GetBaremetalOfferResult, error) {
	var rv GetBaremetalOfferResult
	err := ctx.Invoke("scaleway:index/getBaremetalOffer:getBaremetalOffer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBaremetalOffer.
type GetBaremetalOfferArgs struct {
	IncludeDisabled *bool   `pulumi:"includeDisabled"`
	Name            *string `pulumi:"name"`
	OfferId         *string `pulumi:"offerId"`
	Zone            *string `pulumi:"zone"`
}

// A collection of values returned by getBaremetalOffer.
type GetBaremetalOfferResult struct {
	Bandwidth       int                     `pulumi:"bandwidth"`
	CommercialRange string                  `pulumi:"commercialRange"`
	Cpus            []GetBaremetalOfferCpus `pulumi:"cpus"`
	Disks           []GetBaremetalOfferDisk `pulumi:"disks"`
	// The provider-assigned unique ID for this managed resource.
	Id              string                    `pulumi:"id"`
	IncludeDisabled *bool                     `pulumi:"includeDisabled"`
	Memories        []GetBaremetalOfferMemory `pulumi:"memories"`
	Name            *string                   `pulumi:"name"`
	OfferId         *string                   `pulumi:"offerId"`
	Stock           string                    `pulumi:"stock"`
	Zone            string                    `pulumi:"zone"`
}
