// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetBootscript(ctx *pulumi.Context, args *GetBootscriptArgs, opts ...pulumi.InvokeOption) (*GetBootscriptResult, error) {
	var rv GetBootscriptResult
	err := ctx.Invoke("scaleway:index/getBootscript:getBootscript", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBootscript.
type GetBootscriptArgs struct {
	Architecture *string `pulumi:"architecture"`
	Name         *string `pulumi:"name"`
	NameFilter   *string `pulumi:"nameFilter"`
}

// A collection of values returned by getBootscript.
type GetBootscriptResult struct {
	Architecture string `pulumi:"architecture"`
	BootCmdArgs  string `pulumi:"bootCmdArgs"`
	Dtb          string `pulumi:"dtb"`
	// The provider-assigned unique ID for this managed resource.
	Id           string  `pulumi:"id"`
	Initrd       string  `pulumi:"initrd"`
	Kernel       string  `pulumi:"kernel"`
	Name         *string `pulumi:"name"`
	NameFilter   *string `pulumi:"nameFilter"`
	Organization string  `pulumi:"organization"`
	Public       bool    `pulumi:"public"`
}
