// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetImage(ctx *pulumi.Context, args *GetImageArgs, opts ...pulumi.InvokeOption) (*GetImageResult, error) {
	var rv GetImageResult
	err := ctx.Invoke("scaleway:index/getImage:getImage", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getImage.
type GetImageArgs struct {
	Architecture string  `pulumi:"architecture"`
	MostRecent   *bool   `pulumi:"mostRecent"`
	Name         *string `pulumi:"name"`
	NameFilter   *string `pulumi:"nameFilter"`
}

// A collection of values returned by getImage.
type GetImageResult struct {
	Architecture string `pulumi:"architecture"`
	CreationDate string `pulumi:"creationDate"`
	// The provider-assigned unique ID for this managed resource.
	Id           string  `pulumi:"id"`
	MostRecent   *bool   `pulumi:"mostRecent"`
	Name         string  `pulumi:"name"`
	NameFilter   *string `pulumi:"nameFilter"`
	Organization string  `pulumi:"organization"`
	Public       bool    `pulumi:"public"`
}
