// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupLbIPBeta(ctx *pulumi.Context, args *LookupLbIPBetaArgs, opts ...pulumi.InvokeOption) (*LookupLbIPBetaResult, error) {
	var rv LookupLbIPBetaResult
	err := ctx.Invoke("scaleway:index/getLbIPBeta:getLbIPBeta", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLbIPBeta.
type LookupLbIPBetaArgs struct {
	IpAddress *string `pulumi:"ipAddress"`
	IpId      *string `pulumi:"ipId"`
}

// A collection of values returned by getLbIPBeta.
type LookupLbIPBetaResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id             string  `pulumi:"id"`
	IpAddress      *string `pulumi:"ipAddress"`
	IpId           *string `pulumi:"ipId"`
	LbId           string  `pulumi:"lbId"`
	OrganizationId string  `pulumi:"organizationId"`
	Region         string  `pulumi:"region"`
	Reverse        string  `pulumi:"reverse"`
}
