// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type IP struct {
	pulumi.CustomResourceState

	// The ipv4 address of the ip
	Ip pulumi.StringOutput `pulumi:"ip"`
	// The ipv4 reverse dns
	//
	// Deprecated: use scaleway_ip_reverse_dns resource instead
	Reverse pulumi.StringOutput `pulumi:"reverse"`
	// The server associated with the ip
	Server pulumi.StringOutput `pulumi:"server"`
}

// NewIP registers a new resource with the given unique name, arguments, and options.
func NewIP(ctx *pulumi.Context,
	name string, args *IPArgs, opts ...pulumi.ResourceOption) (*IP, error) {
	if args == nil {
		args = &IPArgs{}
	}
	var resource IP
	err := ctx.RegisterResource("scaleway:index/iP:IP", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIP gets an existing IP resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIP(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IPState, opts ...pulumi.ResourceOption) (*IP, error) {
	var resource IP
	err := ctx.ReadResource("scaleway:index/iP:IP", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IP resources.
type ipState struct {
	// The ipv4 address of the ip
	Ip *string `pulumi:"ip"`
	// The ipv4 reverse dns
	//
	// Deprecated: use scaleway_ip_reverse_dns resource instead
	Reverse *string `pulumi:"reverse"`
	// The server associated with the ip
	Server *string `pulumi:"server"`
}

type IPState struct {
	// The ipv4 address of the ip
	Ip pulumi.StringPtrInput
	// The ipv4 reverse dns
	//
	// Deprecated: use scaleway_ip_reverse_dns resource instead
	Reverse pulumi.StringPtrInput
	// The server associated with the ip
	Server pulumi.StringPtrInput
}

func (IPState) ElementType() reflect.Type {
	return reflect.TypeOf((*ipState)(nil)).Elem()
}

type ipArgs struct {
	// The ipv4 reverse dns
	//
	// Deprecated: use scaleway_ip_reverse_dns resource instead
	Reverse *string `pulumi:"reverse"`
	// The server associated with the ip
	Server *string `pulumi:"server"`
}

// The set of arguments for constructing a IP resource.
type IPArgs struct {
	// The ipv4 reverse dns
	//
	// Deprecated: use scaleway_ip_reverse_dns resource instead
	Reverse pulumi.StringPtrInput
	// The server associated with the ip
	Server pulumi.StringPtrInput
}

func (IPArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ipArgs)(nil)).Elem()
}
