// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type LbFrontendBeta struct {
	pulumi.CustomResourceState

	// ACL rules
	Acls LbFrontendBetaAclArrayOutput `pulumi:"acls"`
	// The load-balancer backend ID
	BackendId pulumi.StringOutput `pulumi:"backendId"`
	// Certificate ID
	CertificateId pulumi.StringPtrOutput `pulumi:"certificateId"`
	// TCP port to listen on the front side
	InboundPort pulumi.IntOutput `pulumi:"inboundPort"`
	// The load-balancer ID
	LbId pulumi.StringOutput `pulumi:"lbId"`
	// The name of the frontend
	Name pulumi.StringOutput `pulumi:"name"`
	// Set the maximum inactivity time on the client side
	TimeoutClient pulumi.StringPtrOutput `pulumi:"timeoutClient"`
}

// NewLbFrontendBeta registers a new resource with the given unique name, arguments, and options.
func NewLbFrontendBeta(ctx *pulumi.Context,
	name string, args *LbFrontendBetaArgs, opts ...pulumi.ResourceOption) (*LbFrontendBeta, error) {
	if args == nil || args.BackendId == nil {
		return nil, errors.New("missing required argument 'BackendId'")
	}
	if args == nil || args.InboundPort == nil {
		return nil, errors.New("missing required argument 'InboundPort'")
	}
	if args == nil || args.LbId == nil {
		return nil, errors.New("missing required argument 'LbId'")
	}
	if args == nil {
		args = &LbFrontendBetaArgs{}
	}
	var resource LbFrontendBeta
	err := ctx.RegisterResource("scaleway:index/lbFrontendBeta:LbFrontendBeta", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLbFrontendBeta gets an existing LbFrontendBeta resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLbFrontendBeta(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LbFrontendBetaState, opts ...pulumi.ResourceOption) (*LbFrontendBeta, error) {
	var resource LbFrontendBeta
	err := ctx.ReadResource("scaleway:index/lbFrontendBeta:LbFrontendBeta", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LbFrontendBeta resources.
type lbFrontendBetaState struct {
	// ACL rules
	Acls []LbFrontendBetaAcl `pulumi:"acls"`
	// The load-balancer backend ID
	BackendId *string `pulumi:"backendId"`
	// Certificate ID
	CertificateId *string `pulumi:"certificateId"`
	// TCP port to listen on the front side
	InboundPort *int `pulumi:"inboundPort"`
	// The load-balancer ID
	LbId *string `pulumi:"lbId"`
	// The name of the frontend
	Name *string `pulumi:"name"`
	// Set the maximum inactivity time on the client side
	TimeoutClient *string `pulumi:"timeoutClient"`
}

type LbFrontendBetaState struct {
	// ACL rules
	Acls LbFrontendBetaAclArrayInput
	// The load-balancer backend ID
	BackendId pulumi.StringPtrInput
	// Certificate ID
	CertificateId pulumi.StringPtrInput
	// TCP port to listen on the front side
	InboundPort pulumi.IntPtrInput
	// The load-balancer ID
	LbId pulumi.StringPtrInput
	// The name of the frontend
	Name pulumi.StringPtrInput
	// Set the maximum inactivity time on the client side
	TimeoutClient pulumi.StringPtrInput
}

func (LbFrontendBetaState) ElementType() reflect.Type {
	return reflect.TypeOf((*lbFrontendBetaState)(nil)).Elem()
}

type lbFrontendBetaArgs struct {
	// ACL rules
	Acls []LbFrontendBetaAcl `pulumi:"acls"`
	// The load-balancer backend ID
	BackendId string `pulumi:"backendId"`
	// Certificate ID
	CertificateId *string `pulumi:"certificateId"`
	// TCP port to listen on the front side
	InboundPort int `pulumi:"inboundPort"`
	// The load-balancer ID
	LbId string `pulumi:"lbId"`
	// The name of the frontend
	Name *string `pulumi:"name"`
	// Set the maximum inactivity time on the client side
	TimeoutClient *string `pulumi:"timeoutClient"`
}

// The set of arguments for constructing a LbFrontendBeta resource.
type LbFrontendBetaArgs struct {
	// ACL rules
	Acls LbFrontendBetaAclArrayInput
	// The load-balancer backend ID
	BackendId pulumi.StringInput
	// Certificate ID
	CertificateId pulumi.StringPtrInput
	// TCP port to listen on the front side
	InboundPort pulumi.IntInput
	// The load-balancer ID
	LbId pulumi.StringInput
	// The name of the frontend
	Name pulumi.StringPtrInput
	// Set the maximum inactivity time on the client side
	TimeoutClient pulumi.StringPtrInput
}

func (LbFrontendBetaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lbFrontendBetaArgs)(nil)).Elem()
}
