// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package scaleway

import (
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type LbIPBeta struct {
	pulumi.CustomResourceState

	// The load-balancer public IP address
	IpAddress pulumi.StringOutput `pulumi:"ipAddress"`
	// The ID of the loadbalancer attached to this IP, if any
	LbId pulumi.StringOutput `pulumi:"lbId"`
	// The organization_id you want to attach the resource to
	OrganizationId pulumi.StringOutput `pulumi:"organizationId"`
	// The region you want to attach the resource to
	Region pulumi.StringOutput `pulumi:"region"`
	// The reverse domain name for this IP
	Reverse pulumi.StringOutput `pulumi:"reverse"`
}

// NewLbIPBeta registers a new resource with the given unique name, arguments, and options.
func NewLbIPBeta(ctx *pulumi.Context,
	name string, args *LbIPBetaArgs, opts ...pulumi.ResourceOption) (*LbIPBeta, error) {
	if args == nil {
		args = &LbIPBetaArgs{}
	}
	var resource LbIPBeta
	err := ctx.RegisterResource("scaleway:index/lbIPBeta:LbIPBeta", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLbIPBeta gets an existing LbIPBeta resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLbIPBeta(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LbIPBetaState, opts ...pulumi.ResourceOption) (*LbIPBeta, error) {
	var resource LbIPBeta
	err := ctx.ReadResource("scaleway:index/lbIPBeta:LbIPBeta", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LbIPBeta resources.
type lbIPBetaState struct {
	// The load-balancer public IP address
	IpAddress *string `pulumi:"ipAddress"`
	// The ID of the loadbalancer attached to this IP, if any
	LbId *string `pulumi:"lbId"`
	// The organization_id you want to attach the resource to
	OrganizationId *string `pulumi:"organizationId"`
	// The region you want to attach the resource to
	Region *string `pulumi:"region"`
	// The reverse domain name for this IP
	Reverse *string `pulumi:"reverse"`
}

type LbIPBetaState struct {
	// The load-balancer public IP address
	IpAddress pulumi.StringPtrInput
	// The ID of the loadbalancer attached to this IP, if any
	LbId pulumi.StringPtrInput
	// The organization_id you want to attach the resource to
	OrganizationId pulumi.StringPtrInput
	// The region you want to attach the resource to
	Region pulumi.StringPtrInput
	// The reverse domain name for this IP
	Reverse pulumi.StringPtrInput
}

func (LbIPBetaState) ElementType() reflect.Type {
	return reflect.TypeOf((*lbIPBetaState)(nil)).Elem()
}

type lbIPBetaArgs struct {
	// The organization_id you want to attach the resource to
	OrganizationId *string `pulumi:"organizationId"`
	// The region you want to attach the resource to
	Region *string `pulumi:"region"`
	// The reverse domain name for this IP
	Reverse *string `pulumi:"reverse"`
}

// The set of arguments for constructing a LbIPBeta resource.
type LbIPBetaArgs struct {
	// The organization_id you want to attach the resource to
	OrganizationId pulumi.StringPtrInput
	// The region you want to attach the resource to
	Region pulumi.StringPtrInput
	// The reverse domain name for this IP
	Reverse pulumi.StringPtrInput
}

func (LbIPBetaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lbIPBetaArgs)(nil)).Elem()
}
