// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getAccountSSHKey(args?: GetAccountSSHKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountSSHKeyResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("scaleway:index/getAccountSSHKey:getAccountSSHKey", {
        "name": args.name,
        "organizationId": args.organizationId,
        "sshKeyId": args.sshKeyId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccountSSHKey.
 */
export interface GetAccountSSHKeyArgs {
    readonly name?: string;
    readonly organizationId?: string;
    readonly sshKeyId?: string;
}

/**
 * A collection of values returned by getAccountSSHKey.
 */
export interface GetAccountSSHKeyResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly organizationId: string;
    readonly publicKey: string;
    readonly sshKeyId: string;
}
