// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBaremetalOffer(args?: GetBaremetalOfferArgs, opts?: pulumi.InvokeOptions): Promise<GetBaremetalOfferResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("scaleway:index/getBaremetalOffer:getBaremetalOffer", {
        "includeDisabled": args.includeDisabled,
        "name": args.name,
        "offerId": args.offerId,
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getBaremetalOffer.
 */
export interface GetBaremetalOfferArgs {
    readonly includeDisabled?: boolean;
    readonly name?: string;
    readonly offerId?: string;
    readonly zone?: string;
}

/**
 * A collection of values returned by getBaremetalOffer.
 */
export interface GetBaremetalOfferResult {
    readonly bandwidth: number;
    readonly commercialRange: string;
    readonly cpus: outputs.GetBaremetalOfferCpus[];
    readonly disks: outputs.GetBaremetalOfferDisk[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly includeDisabled?: boolean;
    readonly memories: outputs.GetBaremetalOfferMemory[];
    readonly name?: string;
    readonly offerId?: string;
    readonly stock: string;
    readonly zone: string;
}
