// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getInstanceImage(args?: GetInstanceImageArgs, opts?: pulumi.InvokeOptions): Promise<GetInstanceImageResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("scaleway:index/getInstanceImage:getInstanceImage", {
        "architecture": args.architecture,
        "imageId": args.imageId,
        "latest": args.latest,
        "name": args.name,
        "organizationId": args.organizationId,
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getInstanceImage.
 */
export interface GetInstanceImageArgs {
    readonly architecture?: string;
    readonly imageId?: string;
    readonly latest?: boolean;
    readonly name?: string;
    readonly organizationId?: string;
    readonly zone?: string;
}

/**
 * A collection of values returned by getInstanceImage.
 */
export interface GetInstanceImageResult {
    readonly additionalVolumeIds: string[];
    readonly architecture?: string;
    readonly creationDate: string;
    readonly defaultBootscriptId: string;
    readonly fromServerId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly imageId?: string;
    readonly latest?: boolean;
    readonly modificationDate: string;
    readonly name?: string;
    readonly organizationId: string;
    readonly public: boolean;
    readonly rootVolumeId: string;
    readonly state: string;
    readonly zone: string;
}
