// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getLbIPBeta(args?: GetLbIPBetaArgs, opts?: pulumi.InvokeOptions): Promise<GetLbIPBetaResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("scaleway:index/getLbIPBeta:getLbIPBeta", {
        "ipAddress": args.ipAddress,
        "ipId": args.ipId,
    }, opts);
}

/**
 * A collection of arguments for invoking getLbIPBeta.
 */
export interface GetLbIPBetaArgs {
    readonly ipAddress?: string;
    readonly ipId?: string;
}

/**
 * A collection of values returned by getLbIPBeta.
 */
export interface GetLbIPBetaResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ipAddress?: string;
    readonly ipId?: string;
    readonly lbId: string;
    readonly organizationId: string;
    readonly region: string;
    readonly reverse: string;
}
