// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRegistryImageBeta(args?: GetRegistryImageBetaArgs, opts?: pulumi.InvokeOptions): Promise<GetRegistryImageBetaResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("scaleway:index/getRegistryImageBeta:getRegistryImageBeta", {
        "imageId": args.imageId,
        "name": args.name,
        "namespaceId": args.namespaceId,
        "organizationId": args.organizationId,
        "region": args.region,
        "tags": args.tags,
    }, opts);
}

/**
 * A collection of arguments for invoking getRegistryImageBeta.
 */
export interface GetRegistryImageBetaArgs {
    readonly imageId?: string;
    readonly name?: string;
    readonly namespaceId?: string;
    readonly organizationId?: string;
    readonly region?: string;
    readonly tags?: string[];
}

/**
 * A collection of values returned by getRegistryImageBeta.
 */
export interface GetRegistryImageBetaResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly imageId?: string;
    readonly name?: string;
    readonly namespaceId: string;
    readonly organizationId: string;
    readonly region: string;
    readonly size: number;
    readonly tags: string[];
    readonly visibility: string;
}
