// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getRegistryNamespaceBeta(args?: GetRegistryNamespaceBetaArgs, opts?: pulumi.InvokeOptions): Promise<GetRegistryNamespaceBetaResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("scaleway:index/getRegistryNamespaceBeta:getRegistryNamespaceBeta", {
        "name": args.name,
        "namespaceId": args.namespaceId,
        "region": args.region,
    }, opts);
}

/**
 * A collection of arguments for invoking getRegistryNamespaceBeta.
 */
export interface GetRegistryNamespaceBetaArgs {
    readonly name?: string;
    readonly namespaceId?: string;
    readonly region?: string;
}

/**
 * A collection of values returned by getRegistryNamespaceBeta.
 */
export interface GetRegistryNamespaceBetaResult {
    readonly description: string;
    readonly endpoint: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly isPublic: boolean;
    readonly name?: string;
    readonly namespaceId?: string;
    readonly organizationId: string;
    readonly region?: string;
}
