// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class LbIPBeta extends pulumi.CustomResource {
    /**
     * Get an existing LbIPBeta resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LbIPBetaState, opts?: pulumi.CustomResourceOptions): LbIPBeta {
        return new LbIPBeta(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'scaleway:index/lbIPBeta:LbIPBeta';

    /**
     * Returns true if the given object is an instance of LbIPBeta.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LbIPBeta {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LbIPBeta.__pulumiType;
    }

    /**
     * The load-balancer public IP address
     */
    public /*out*/ readonly ipAddress!: pulumi.Output<string>;
    /**
     * The ID of the loadbalancer attached to this IP, if any
     */
    public /*out*/ readonly lbId!: pulumi.Output<string>;
    /**
     * The organization_id you want to attach the resource to
     */
    public readonly organizationId!: pulumi.Output<string>;
    /**
     * The region you want to attach the resource to
     */
    public readonly region!: pulumi.Output<string>;
    /**
     * The reverse domain name for this IP
     */
    public readonly reverse!: pulumi.Output<string>;

    /**
     * Create a LbIPBeta resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: LbIPBetaArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LbIPBetaArgs | LbIPBetaState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as LbIPBetaState | undefined;
            inputs["ipAddress"] = state ? state.ipAddress : undefined;
            inputs["lbId"] = state ? state.lbId : undefined;
            inputs["organizationId"] = state ? state.organizationId : undefined;
            inputs["region"] = state ? state.region : undefined;
            inputs["reverse"] = state ? state.reverse : undefined;
        } else {
            const args = argsOrState as LbIPBetaArgs | undefined;
            inputs["organizationId"] = args ? args.organizationId : undefined;
            inputs["region"] = args ? args.region : undefined;
            inputs["reverse"] = args ? args.reverse : undefined;
            inputs["ipAddress"] = undefined /*out*/;
            inputs["lbId"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(LbIPBeta.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LbIPBeta resources.
 */
export interface LbIPBetaState {
    /**
     * The load-balancer public IP address
     */
    readonly ipAddress?: pulumi.Input<string>;
    /**
     * The ID of the loadbalancer attached to this IP, if any
     */
    readonly lbId?: pulumi.Input<string>;
    /**
     * The organization_id you want to attach the resource to
     */
    readonly organizationId?: pulumi.Input<string>;
    /**
     * The region you want to attach the resource to
     */
    readonly region?: pulumi.Input<string>;
    /**
     * The reverse domain name for this IP
     */
    readonly reverse?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a LbIPBeta resource.
 */
export interface LbIPBetaArgs {
    /**
     * The organization_id you want to attach the resource to
     */
    readonly organizationId?: pulumi.Input<string>;
    /**
     * The region you want to attach the resource to
     */
    readonly region?: pulumi.Input<string>;
    /**
     * The reverse domain name for this IP
     */
    readonly reverse?: pulumi.Input<string>;
}
