// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SecurityGroup extends pulumi.CustomResource {
    /**
     * Get an existing SecurityGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecurityGroupState, opts?: pulumi.CustomResourceOptions): SecurityGroup {
        return new SecurityGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'scaleway:index/securityGroup:SecurityGroup';

    /**
     * Returns true if the given object is an instance of SecurityGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecurityGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecurityGroup.__pulumiType;
    }

    /**
     * The description of the security group
     */
    public readonly description!: pulumi.Output<string>;
    /**
     * Add default security group rules
     */
    public readonly enableDefaultSecurity!: pulumi.Output<boolean | undefined>;
    /**
     * Default inbound traffic policy for this security group
     */
    public readonly inboundDefaultPolicy!: pulumi.Output<string | undefined>;
    /**
     * The name of the security group
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Default outbound traffic policy for this security group
     */
    public readonly outboundDefaultPolicy!: pulumi.Output<string | undefined>;
    /**
     * Mark security group as stateful
     */
    public readonly stateful!: pulumi.Output<boolean | undefined>;

    /**
     * Create a SecurityGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecurityGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecurityGroupArgs | SecurityGroupState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as SecurityGroupState | undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["enableDefaultSecurity"] = state ? state.enableDefaultSecurity : undefined;
            inputs["inboundDefaultPolicy"] = state ? state.inboundDefaultPolicy : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["outboundDefaultPolicy"] = state ? state.outboundDefaultPolicy : undefined;
            inputs["stateful"] = state ? state.stateful : undefined;
        } else {
            const args = argsOrState as SecurityGroupArgs | undefined;
            if (!args || args.description === undefined) {
                throw new Error("Missing required property 'description'");
            }
            inputs["description"] = args ? args.description : undefined;
            inputs["enableDefaultSecurity"] = args ? args.enableDefaultSecurity : undefined;
            inputs["inboundDefaultPolicy"] = args ? args.inboundDefaultPolicy : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["outboundDefaultPolicy"] = args ? args.outboundDefaultPolicy : undefined;
            inputs["stateful"] = args ? args.stateful : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(SecurityGroup.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecurityGroup resources.
 */
export interface SecurityGroupState {
    /**
     * The description of the security group
     */
    readonly description?: pulumi.Input<string>;
    /**
     * Add default security group rules
     */
    readonly enableDefaultSecurity?: pulumi.Input<boolean>;
    /**
     * Default inbound traffic policy for this security group
     */
    readonly inboundDefaultPolicy?: pulumi.Input<string>;
    /**
     * The name of the security group
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Default outbound traffic policy for this security group
     */
    readonly outboundDefaultPolicy?: pulumi.Input<string>;
    /**
     * Mark security group as stateful
     */
    readonly stateful?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a SecurityGroup resource.
 */
export interface SecurityGroupArgs {
    /**
     * The description of the security group
     */
    readonly description: pulumi.Input<string>;
    /**
     * Add default security group rules
     */
    readonly enableDefaultSecurity?: pulumi.Input<boolean>;
    /**
     * Default inbound traffic policy for this security group
     */
    readonly inboundDefaultPolicy?: pulumi.Input<string>;
    /**
     * The name of the security group
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Default outbound traffic policy for this security group
     */
    readonly outboundDefaultPolicy?: pulumi.Input<string>;
    /**
     * Mark security group as stateful
     */
    readonly stateful?: pulumi.Input<boolean>;
}
