// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SecurityGroupRule extends pulumi.CustomResource {
    /**
     * Get an existing SecurityGroupRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecurityGroupRuleState, opts?: pulumi.CustomResourceOptions): SecurityGroupRule {
        return new SecurityGroupRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'scaleway:index/securityGroupRule:SecurityGroupRule';

    /**
     * Returns true if the given object is an instance of SecurityGroupRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecurityGroupRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecurityGroupRule.__pulumiType;
    }

    /**
     * The action to take when the security group rule is triggered (accept or drop)
     */
    public readonly action!: pulumi.Output<string>;
    /**
     * The direction the traffic is affected (inbound or outbound)
     */
    public readonly direction!: pulumi.Output<string>;
    /**
     * The ip range affected by the security group rule
     */
    public readonly ipRange!: pulumi.Output<string>;
    /**
     * The port affected by the security group rule
     */
    public readonly port!: pulumi.Output<number | undefined>;
    /**
     * The protocol of the security group rule (ICMP, TCP or UDP)
     */
    public readonly protocol!: pulumi.Output<string>;
    /**
     * The security group this rule is attached to
     */
    public readonly securityGroup!: pulumi.Output<string>;

    /**
     * Create a SecurityGroupRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecurityGroupRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecurityGroupRuleArgs | SecurityGroupRuleState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as SecurityGroupRuleState | undefined;
            inputs["action"] = state ? state.action : undefined;
            inputs["direction"] = state ? state.direction : undefined;
            inputs["ipRange"] = state ? state.ipRange : undefined;
            inputs["port"] = state ? state.port : undefined;
            inputs["protocol"] = state ? state.protocol : undefined;
            inputs["securityGroup"] = state ? state.securityGroup : undefined;
        } else {
            const args = argsOrState as SecurityGroupRuleArgs | undefined;
            if (!args || args.action === undefined) {
                throw new Error("Missing required property 'action'");
            }
            if (!args || args.direction === undefined) {
                throw new Error("Missing required property 'direction'");
            }
            if (!args || args.ipRange === undefined) {
                throw new Error("Missing required property 'ipRange'");
            }
            if (!args || args.protocol === undefined) {
                throw new Error("Missing required property 'protocol'");
            }
            if (!args || args.securityGroup === undefined) {
                throw new Error("Missing required property 'securityGroup'");
            }
            inputs["action"] = args ? args.action : undefined;
            inputs["direction"] = args ? args.direction : undefined;
            inputs["ipRange"] = args ? args.ipRange : undefined;
            inputs["port"] = args ? args.port : undefined;
            inputs["protocol"] = args ? args.protocol : undefined;
            inputs["securityGroup"] = args ? args.securityGroup : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(SecurityGroupRule.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecurityGroupRule resources.
 */
export interface SecurityGroupRuleState {
    /**
     * The action to take when the security group rule is triggered (accept or drop)
     */
    readonly action?: pulumi.Input<string>;
    /**
     * The direction the traffic is affected (inbound or outbound)
     */
    readonly direction?: pulumi.Input<string>;
    /**
     * The ip range affected by the security group rule
     */
    readonly ipRange?: pulumi.Input<string>;
    /**
     * The port affected by the security group rule
     */
    readonly port?: pulumi.Input<number>;
    /**
     * The protocol of the security group rule (ICMP, TCP or UDP)
     */
    readonly protocol?: pulumi.Input<string>;
    /**
     * The security group this rule is attached to
     */
    readonly securityGroup?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SecurityGroupRule resource.
 */
export interface SecurityGroupRuleArgs {
    /**
     * The action to take when the security group rule is triggered (accept or drop)
     */
    readonly action: pulumi.Input<string>;
    /**
     * The direction the traffic is affected (inbound or outbound)
     */
    readonly direction: pulumi.Input<string>;
    /**
     * The ip range affected by the security group rule
     */
    readonly ipRange: pulumi.Input<string>;
    /**
     * The port affected by the security group rule
     */
    readonly port?: pulumi.Input<number>;
    /**
     * The protocol of the security group rule (ICMP, TCP or UDP)
     */
    readonly protocol: pulumi.Input<string>;
    /**
     * The security group this rule is attached to
     */
    readonly securityGroup: pulumi.Input<string>;
}
